// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// This file is automatically generated by AudioConstantsGenerator.cs

public static class Audio
{
    public const string Jump = "Jump";
    public const string Land = "Land";
    public const string Dash = "Dash";
}
